COLS EQU P0
ROWS EQU P1
KEYPAD EQU P2

SPIELER1 EQU 020h
SPIELER2 EQU 028h
SPIELER2AKTIV EQU 030h

loop:
MOV R0, #SPIELER1
CALL display
MOV R0, #spieler2
CALL display
AJMP loop

; Display gibt das Spielbrett aus. Falls in #SPIELER2AKTIV FFh steht, werden beide Zustände ausgegeben
display:
MOV A, SPIELER2AKTIV
ANL A, SPIELER2
ORL A, SPIELER1
MOV COLS, A
SETB ROWS.0
CLR ROWS.0
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 1
ORL A, SPIELER1 + 1
MOV COLS, A
SETB ROWS.1
CLR ROWS.1
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 2
ORL A, SPIELER1 + 2
MOV COLS, A
SETB ROWS.2
CLR ROWS.2
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 3
ORL A, SPIELER1 + 3
MOV COLS, A
SETB ROWS.3
CLR ROWS.3
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 4
ORL A, SPIELER1 + 4
MOV COLS, A
SETB ROWS.4
CLR ROWS.4
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 5
ORL A, SPIELER1 + 5
MOV COLS, A
SETB ROWS.5
CLR ROWS.5
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 6
ORL A, SPIELER1 + 6
MOV COLS, A
SETB ROWS.6
CLR ROWS.6
MOV A, SPIELER2AKTIV
ANL A, SPIELER2 + 7
ORL A, SPIELER1 + 7
MOV COLS, A
SETB ROWS.7
CLR ROWS.7
RET